export const CHECKLISTS = [
  {
    id: "private-party",
    label: "Private Party Checklist",
    items: [
      { text: "Table" },
      { text: "2 big black table cloths" },
      { text: "Raw bar" },
      { text: "Table risers" },
      { text: "Trash can" },
      { text: "Trash bags" },
      { text: "Oyster knife" },
      { text: "Lemon knife" },
      { text: "Cutting board" },
      { text: "Towels" },
      { text: "Black catering gloves" },
      { text: "Lemons (20)" },
      { text: "Catering napkins" },
      { text: "Palm leaf plates" },
      { text: "2 Silver buckets for raw bar" },
      { text: "Mignonettes (2)" },
      { text: "Hot sauce (2)" },
      { text: "Biz cards" },
      { text: "Oysters" },
      { text: "2 coolers of ice" },
    ],
  },
  {
    id: "cleanup",
    label: "Cleanup and Inventory after Events",
    items: [
      { text: "Wash all dirty dishes" },
      { text: "Dry all clean dishes" },
      { text: "Put away clean dishes in their correct location" },
      { text: "Put away soap and sponge" },
      { text: "Take out the trash and replace trash bag" },
      { text: "Dry goods — write totals on spreadsheet:", isHeading: true },
      { text: "Rolls", isSubItem: true },
      { text: "Propane", isSubItem: true },
      { text: "Oyster Bowls", isSubItem: true },
      { text: "Lobster Boats", isSubItem: true },
      { text: "Gloves", isSubItem: true },
      { text: "Napkins", isSubItem: true },
      { text: "Branded Deli Paper", isSubItem: true },
      { text: "Wet goods — write totals on spreadsheet:", isHeading: true },
      { text: "Lobster meat", isSubItem: true },
      { text: "Oysters", isSubItem: true },
      { text: "Butter", isSubItem: true },
      { text: "Lemons", isSubItem: true },
      { text: "1 bag of lobster = 8 LBS", isNote: true },
      { text: "1 block of butter = 1 LB", isNote: true },
    ],
  },
  {
    id: "smorgasburg",
    label: "Smorgasburg Checklist",
    items: [
      { text: "Tent" },
      { text: "Tent side rails" },
      { text: "Tent side signage" },
      { text: "Tables (3)" },
      { text: "Risers for tables" },
      { text: "Oil Tablecloths (3)" },
      { text: "Black fitted tablecloths (3)" },
      { text: "Clamps for tablecloths (9)" },
      { text: "Bank" },
      { text: "Cash register" },
      { text: "iPad" },
      { text: "iPad stand" },
      { text: "Trash cans" },
      { text: "Trash bags" },
      { text: "Metal raw bar display" },
      { text: "Grill" },
      { text: "Grill hose" },
      { text: "Propane" },
      { text: "6 hotel pan for melted butter" },
      { text: "⅓ hotel pan for lobster meat" },
      { text: "Butter brush (2)" },
      { text: "Scoop (2)" },
      { text: "Oyster knives" },
      { text: "Lemon knives" },
      { text: "Paprika" },
      { text: "Bowls for oysters (2 sleeves)" },
      { text: "Boats for lobster roll (2 sleeves)" },
      { text: "Gloves" },
      { text: "Napkins" },
      { text: "Thermometer" },
      { text: "Tip jars" },
      { text: "Empty cooler for ice discard" },
      { text: "Mignonette bottles (6)" },
      { text: "Hot sauce bottles (6)" },
      { text: "Tent weights (2)" },
      { text: "Business cards" },
      { text: "Oysters" },
      { text: "Crushed ice" },
      { text: "Lobster meat" },
      { text: "Case of lemons" },
      { text: "Cutting boards (2)" },
      { text: "Towels (30)" },
      { text: "Water for hand washing" },
      { text: "Butter (10 LB)" },
      { text: "Rolls (500 / 32 packs)" },
    ],
  },
];
